### PR TITLE
Update fend.yml

### PR DESCRIPTION
**Pull request by ivanteso**

### CODE REVIEW

**Comment by ellemwano** [comment]
Thank you Ivan and impressive work! Well done! 
For some reason the banner link does not work. I thought it was a typo but no. We'll have a look tomorrow.

**Comment by ellemwano** [comment]
Perfect! It works now. Thank you. I had forgotten that jpg at the end too

**Comment by ivanteso** [comment]
I think I just forhot `.jpg` at the end of the ink, I thought it was included when I've copied it. I've fix it right now ;)

**Comment by ellemwano** [comment]
Yes. That was it :). Thanks

**Pull request merged**
